/**
 * Mock API responses for Playwright E2E tests.
 * Derived from src/lib/mocks but plain JSON (no TS imports).
 */

export const TRAVERSAL_RESPONSE = {
	nodes: [
		{
			id: 'anskaffelsesforskriften:16-10',
			type: 'provision',
			label: 'FOA §16-10',
			subtitle: 'Bruk av andre enheters kapasitet',
			citations: 12,
			regulation: 'new',
			iteration: 1,
			isSeed: true,
			isDelimitation: false,
		},
		{
			id: 'anskaffelsesforskriften:17-1',
			type: 'provision',
			label: 'FOA §17-1',
			subtitle: 'Krav til dokumentasjon',
			citations: 8,
			regulation: 'new',
			iteration: 1,
			isSeed: true,
			isDelimitation: false,
		},
		{
			id: 'kofa:2023/456',
			type: 'kofa_case',
			label: '2023/456',
			subtitle: 'ESPD + støttende virksomhet',
			date: '2023-06-15',
			outcome: 'Brudd',
			category: 'A',
			signals: { ref: true, fts: true, vec: true },
			citations: 3,
			regulation: 'new',
			iteration: 1,
			isSeed: false,
			isDelimitation: false,
			detail: 'Nemnda fant brudd ved aksept av ESPD som tilstrekkelig dokumentasjon.',
		},
		{
			id: 'kofa:2022/789',
			type: 'kofa_case',
			label: '2022/789',
			subtitle: 'Forpliktelseserklæring — tidspunkt',
			date: '2022-11-22',
			outcome: 'Ikke brudd',
			category: 'A',
			signals: { ref: true, fts: true, vec: true },
			citations: 7,
			regulation: 'new',
			iteration: 1,
			isSeed: false,
			isDelimitation: false,
			detail: 'Nemnda aksepterte ettersending av forpliktelseserklæring.',
		},
		{
			id: 'kofa:2021/234',
			type: 'kofa_case',
			label: '2021/234',
			subtitle: 'Kvalifikasjonskrav og rådighet',
			date: '2021-03-10',
			outcome: 'Brudd',
			category: 'B',
			signals: { ref: true, fts: true, vec: false },
			citations: 5,
			regulation: 'new',
			iteration: 1,
			isSeed: false,
			isDelimitation: false,
		},
		{
			id: 'kofa:2020/567',
			type: 'kofa_case',
			label: '2020/567',
			subtitle: 'Binær vs. kvantitativ rådighet',
			date: '2020-08-05',
			outcome: 'Ikke brudd',
			category: 'B',
			signals: { ref: true, fts: false, vec: true },
			citations: 4,
			regulation: 'new',
			iteration: 1,
			isSeed: false,
			isDelimitation: false,
		},
		{
			id: 'kofa:2019/890',
			type: 'kofa_case',
			label: '2019/890',
			subtitle: 'Ettersending av dokumentasjon',
			date: '2019-05-20',
			outcome: 'Ikke brudd',
			category: 'C',
			signals: { ref: false, fts: true, vec: false },
			citations: 2,
			regulation: 'new',
			iteration: 1,
			isSeed: false,
			isDelimitation: true,
		},
		{
			id: 'kofa:2018/123',
			type: 'kofa_case',
			label: '2018/123',
			subtitle: 'Grunnleggende om forpliktelseserklæring',
			date: '2018-02-14',
			outcome: 'Brudd',
			category: 'A',
			signals: { ref: true, fts: true, vec: true },
			citations: 12,
			regulation: 'new',
			iteration: 1,
			isSeed: false,
			isDelimitation: false,
		},
		{
			id: 'kofa:2015/345',
			type: 'kofa_case',
			label: '2015/345',
			subtitle: 'Støttende virksomhet (gammel FOA)',
			date: '2015-09-30',
			outcome: 'Brudd',
			category: 'C',
			signals: { ref: true, fts: false, vec: false },
			citations: 3,
			regulation: 'old',
			iteration: 1,
			isSeed: false,
			isDelimitation: false,
		},
		{
			id: 'eu:C-324/14',
			type: 'eu_case',
			label: 'C-324/14',
			subtitle: 'Partner Apelski',
			date: '2016-05-10',
			category: 'A',
			signals: { ref: true, fts: false, vec: true },
			citations: 8,
			iteration: 1,
			isSeed: false,
			isDelimitation: false,
			directive: 'Art. 63',
		},
	],
	edges: [
		{ from: 'kofa:2023/456', to: 'anskaffelsesforskriften:16-10', valence: 'unknown' },
		{ from: 'kofa:2023/456', to: 'anskaffelsesforskriften:17-1', valence: 'unknown' },
		{ from: 'kofa:2022/789', to: 'anskaffelsesforskriften:16-10', valence: 'unknown' },
		{ from: 'kofa:2021/234', to: 'anskaffelsesforskriften:16-10', valence: 'unknown' },
		{ from: 'kofa:2020/567', to: 'anskaffelsesforskriften:16-10', valence: 'unknown' },
		{ from: 'kofa:2018/123', to: 'anskaffelsesforskriften:16-10', valence: 'unknown' },
		{ from: 'kofa:2018/123', to: 'anskaffelsesforskriften:17-1', valence: 'unknown' },
		{ from: 'kofa:2023/456', to: 'kofa:2022/789', valence: 'distinguishing' },
		{ from: 'kofa:2023/456', to: 'kofa:2018/123', valence: 'confirming' },
		{ from: 'kofa:2022/789', to: 'kofa:2018/123', valence: 'confirming' },
		{ from: 'kofa:2023/456', to: 'eu:C-324/14', valence: 'unknown' },
		{ from: 'kofa:2018/123', to: 'eu:C-324/14', valence: 'unknown' },
	],
	gaps: [
		{ provision1: 'FOA §16-10', provision2: 'FOA §17-1', count: 3 },
		{ provision1: 'FOA §16-10', provision2: 'FOA §16-3', count: 0 },
	],
	stats: {
		total: 7,
		categoryA: 3,
		categoryB: 2,
		categoryC: 2,
		delimitations: 1,
	},
};

/** Smaller response for single-provision search */
export const SINGLE_PROVISION_RESPONSE = {
	nodes: [
		TRAVERSAL_RESPONSE.nodes[0], // FOA §16-10
		TRAVERSAL_RESPONSE.nodes[2], // 2023/456
		TRAVERSAL_RESPONSE.nodes[4], // 2021/234
	],
	edges: [
		{ from: 'kofa:2023/456', to: 'anskaffelsesforskriften:16-10', valence: 'unknown' },
		{ from: 'kofa:2021/234', to: 'anskaffelsesforskriften:16-10', valence: 'unknown' },
	],
	gaps: [],
	stats: { total: 2, categoryA: 1, categoryB: 1, categoryC: 0, delimitations: 0 },
};

/** Case detail for 2023/456 */
export const CASE_DETAIL = {
	sak_nr: '2023/456',
	avgjoerelse: 'Brudd på anskaffelsesforskriften § 16-10',
	saken_gjelder: 'ESPD og støttende virksomhet',
	avsluttet: '2023-06-15',
	innklaget: 'Viken fylkeskommune',
	klager: 'Bygg AS',
	sakstype: 'Rådgivende sak',
	regelverk: 'anskaffelsesforskriften',
	summary: null,
	paragraphs: [
		{ paragraph_number: 1, section: 'Bakgrunn', text: 'Saken gjelder en konkurranse om bygging av skole.' },
		{ paragraph_number: 2, section: 'Bakgrunn', text: 'Klager anfører at innklagede brøt regelverket.' },
		{ paragraph_number: 3, section: 'Rettslige spørsmål', text: 'Spørsmålet er om ESPD er tilstrekkelig dokumentasjon.' },
		{ paragraph_number: 4, section: 'Nemndas vurdering', text: 'Nemnda finner at ESPD alene ikke oppfyller kravene i § 16-10.' },
		{ paragraph_number: 5, section: 'Konklusjon', text: 'Innklagede har brutt anskaffelsesforskriften § 16-10.' },
	],
	law_references: [
		{ law_name: 'anskaffelsesforskriften', law_section: '16-10', context: 'Bruk av andre enheters kapasitet', regulation_version: 'new' },
	],
	case_references: [
		{ to_sak_nr: '2022/789', context: 'Tilsvarende vurdering av ESPD' },
	],
	eu_references: [
		{ eu_case_id: 'C-324/14', eu_case_name: 'Partner Apelski', context: 'Krav til dokumentasjon av kapasitet' },
	],
};
